### PR TITLE
DB_init

### PR DESCRIPTION
**Pull request by Kirethik**
Created  a db_init .js file to intialize a default sql database

### CODE REVIEW

**Review by Thanus-Kumaar — APPROVED** [review]
Really great job @Kirethik . Very clean code 🔥 .

**Comment by Thanus-Kumaar** [comment]
@Kirethik I want to ask you something, usually create connection function will ask for a database right? There should be an error popping up, but when I tested it locally, it was working fine. Can you explain what is the difference?

**Comment by Kirethik** [comment]
Whenever server.js is executed, it first runs Db_init.js, which checks if the database or tables exist. If they don't, it creates them. This has been done by changing the package.json file. This prevents error from popping out

**Pull request merged**
